module:
  block: 0
  breakpoint: 0
  codesprint_deploy: 0
  coffee: 0
  ctools: 0
  dblog: 0
  dynamic_page_cache: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  image: 0
  layout_plugin: 0
  node: 0
  page_cache: 0
  page_manager: 0
  panels: 0
  panels_ipe: 0
  system: 0
  text: 0
  toolbar: 0
  update: 0
  user: 0
  minimal: 1000
theme:
  stark: 0
  stable: 0
  classy: 0
  seven: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
